# Generated by Django 5.1.1 on 2024-10-21 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='objets', to='accounts.user'),
        ),
    ]
